### ISSUE TITLE
How to invoke 'ipfs files' commands?

### ISSUE THREAD

**Issue by IOsetting** [ipfs/go-ipfs-http-client#109]
I am writing a Go script to add real-time HLS live video segments to a remote IPFS machine, while I am using this client, I cannot find the file operation commands like  `ipfs files cp`, `ipfs files rm`, `ipfs files mkdir` and `ipfs files ls`. 
So far I can only use `api.Unixfs().Add()`, but the the pinned file names show in CIDs which carry no time information, I cannot unpin the files that created before certain time point.
Is there any way to invoke those commands? 

Thanks,

**Comment by jacobheun** [comment]
Can you please ask on the forums https://discuss.ipfs.io, if there's an issue feel free to open a new issue.
