### ISSUE TITLE
not implements the latest ipfs/interface-go-ipfs-core version 

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs-http-client#113]
if used this project with the latest ipfs/interface-go-ipfs-core@v0.3.0 
your source will build failed

i fixed it in a fork.
at the same time it also fixed issue #26

if you want i can pr the source

**Comment by jacobheun** [comment]
We'd welcome a PR

**Comment by godcong** [comment]
Pull reqeust some test casse was failed.
Related　#116

**Comment by aschmahmann** [comment]
closed by #117
