### ISSUE TITLE
Export function `request` to access `RequestBuilder`

### ISSUE THREAD

**Issue by hinshun** [ipfs/go-ipfs-http-client#12]
Since `RequestBuilder` has no public constructor or access to modify `shell *HttpApi`, there isn't a way to use this package to send a request outside of what's defined in `iface.CoreAPI`.

Specifically, I'd like to request for the daemon's peer ID over the API, which I had access to in `go-ipfs-api`:
https://github.com/ipfs/go-ipfs-api/blob/master/shell.go#L112-L116

**Comment by Stebalien** [comment]
I agree we should probably expose this (possibly after some interface
design work) but, for the moment, you can get the peer ID by running:

    self, err := api.Key().Self(ctx)
    if err != nil {
    	panic(err)
    }
    id := self.ID()

**Comment by hinshun** [comment]
Thank you! That works for me.
