### ISSUE TITLE
Not compatible with `github.com/ipfs/kube@v0.18.1`

### ISSUE THREAD

**Issue by kylos101** [ipfs/go-ipfs-http-client#167]
## Description

Projects that depend on ipfs/kubo@v0.18.1 cannot use ipfs/go-ipfs-http-client@v0.4.0. If we try, we get errors like:

```
go build .
# github.com/libp2p/go-libp2p-core/network
../../../go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.20.1/network/rcmgr.go:166:27: network.NullResourceManager (type) is not an expression

go mod why github.com/libp2p/go-libp2p-core/network
# github.com/libp2p/go-libp2p-core/network
github.com/ipfs/go-ipfs-http-client
github.com/libp2p/go-libp2p-core/network
```

ipfs/go-ipfs-http-client depends on:

https://github.com/ipfs/go-ipfs-http-client/blob/171fcd55e3b743c38fb9d78a34a3a703ee0b5e89/go.mod#L12

Which depends on:

https://github.com/ipfs/go-ipfs-http-client/blob/171fcd55e3b743c38fb9d78a34a3a703ee0b5e89/go.mod#L15

But is archived and contains deprecated methods like:

https://github.com/libp2p/go-libp2p-core/blob/654214c1b3401c0363ef464ce9db7e1b04a7ef3f/network/rcmgr.go#L165-L166

## Potential next steps?

1. [Refactor ipfs/interface-go-ipfs-core](https://github.com/ipfs/interface-go-ipfs-core/blob/455c16d43cca0a2ea6949f71bf57c08d9560d5ac/go.mod#L11) to depend on github.com/libp2p/go-libp2p@v0.24.2, and use its core package instead of github.com/libp2p/go-libp2p-core@v0.8.6
2. Update ipfs/go-ipfs-http-client to use the new ipfs/interface-go-ipfs-core using github.com/libp2p/go-libp2p@v0.24.2

## Anything else

I wanted to surface an issue to the community to get it's corresponding guidance. Let me know what you think? :pray:

**Comment by philwinder** [comment]
Commenting to subscribe to this issue. https://github.com/filecoin-project/bacalhau cannot upgrade kubo until this is fixed, because we also use this http client.
