### ISSUE TITLE
v0.6.0 Routing API errors

### ISSUE THREAD

**Issue by avislash** [ipfs/go-ipfs-http-client#182]
After upgrading to go-ipfs-http-client v0.6.0 I recieve the following errors when attemping to run my program
```
# github.com/ipfs/go-ipfs-http-client
../../go/pkg/mod/github.com/ipfs/go-ipfs-http-client@v0.6.0/api.go:214:9: cannot use (*RoutingAPI)(api) (value of type *RoutingAPI) as iface.RoutingAPI value in return statement: *RoutingAPI does not implement iface.RoutingAPI (wrong type for method Put)
                have Put(context.Context, string, []byte) error
                want Put(context.Context, string, []byte, ...options.RoutingPutOption) error
../../go/pkg/mod/github.com/ipfs/go-ipfs-http-client@v0.6.0/dag.go:37:16: undefined: format.DefaultBlockDecoder
../../go/pkg/mod/github.com/ipfs/go-ipfs-http-client@v0.6.0/pin.go:204:16: cannot use &pinVerifyRes{…} (value of type *pinVerifyRes) as iface.PinStatus value in send: *pinVerifyRes does not implement iface.PinStatus (missing method Err)
```

**Comment by aschmahmann** [comment]
This repo is being moved into [kubo](https://github.com/ipfs/kubo) as discussed in https://github.com/ipfs/kubo/issues/9124. The latest version of kubo master has `client/rpc` which is where this code has been moved.

There will be a kubo v0.21.0-rc1 later this week that you can use. Note that once this release is out the plan is to merge https://github.com/ipfs/go-ipfs-http-client/pull/180 (which will forward all types, etc. from this repo to kubo) and then archive this repo.

cc @Jorropo
