### ISSUE TITLE
want use this api in different machine

### ISSUE THREAD

**Issue by godcong** [ipfs/go-ipfs-http-client#24]
the `api` file can only used in the same machine.
if you are running in the docker. 
you cant visit the `api` file out of the container.
so we need create the api with a string address as you know.
i add a pull request to added a create function

ps: i found a path join miss in windows. so i fixed it.

pull path:
>https://github.com/ipfs/go-ipfs-http-client/pull/23

**Comment by Stebalien** [comment]
You can just construct a multiaddr and then pass that into `NewApi`.

**Comment by godcong** [comment]
that's ok.
