### ISSUE TITLE
don't assume http

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs-http-client#4]
rename this to something better than doesnt assume http.

**Comment by Kubuxu** [comment]
I think the aim of this client is to provide interface-go-core-api based on current http api.
We will probably have another one consuming RPC API.

**Comment by whyrusleeping** [comment]
but then we would have to rewrite *all* of this code just for a different transport layer. That seems incredibly silly and wasteful. All we really need to do is reimplement the `request` method to be roundtripped by something else, and the rest of the code should remain the same.

**Comment by Kubuxu** [comment]
I think binding this over HTTP API (cli API) is so unique that if we have different transport/protocol it will have to be implemented quite differently.

This is essentially a translation layer instead of bindings if APIs were 1:1 mapping of each other.

**Comment by magik6k** [comment]
The name comes from https://github.com/ipfs/go-ipfs-api/issues/139

The RPC layer will likely not expose http-api (core/commands), but CoreAPI directly, so the code will be quite different.

Also, depending on the mechanism we pick, it should be possible to just auto-generate large portion of RPC handling code.

For API clients I plan to create another library, which picks the best way to talk to ipfs (http api / rpc / full node / node on libp2p daemon / etc.)
