### ISSUE TITLE
Creating client without IPFS_PATH leads to nil

### ISSUE THREAD

**Issue by hinshun** [ipfs/go-ipfs-http-client#7]
If the default `~/.ipfs`, `IPFS_PATH` env var, or `ipfspath` function arg passed to `NewPathApi` is a non-existent directory, it will return `nil` error and `nil` client.

A common pattern in golang is this:
```
cln, err := httpapi.NewLocalApi()
if err != nil {
  return err
}

// cln.Unixfs().Add ...
```

But that becomes a nil pointer reference. Curious why `os.IsNotExist` errors are hidden here:
https://github.com/ipfs/go-ipfs-http-client/blob/master/api.go#L56-L59

**Comment by Stebalien** [comment]
This probably comes from the fact that this function used to return _no_ error. I agree we should return some kind of `ErrNotRunning`.
