### ISSUE TITLE
Stat call missing in UnixFS

### ISSUE THREAD

**Issue by dokterbob** [ipfs/go-ipfs-http-client#78]
The equivalent of https://docs.ipfs.io/reference/api/cli/#ipfs-files-stat, returns stuff like:

```json
{
"Hash":"QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ",
"Size":0,
"CumulativeSize":443417,
"Blocks":1,
"Type":"directory"
}
```
and
```json
{
"Hash":"Qmd286K6pohQcTKYqnS1YhWrCiS4gz7Xi34sdwMe9USZ7u",
"Size":443230,
"CumulativeSize":443362,
"Blocks":2,
"Type":"file"
}
```

**Comment by dokterbob** [comment]
I suppse we return:

```golang
type FileStat struct {
    Cid cid.Cid
    Blocks int
    Size int
    CumulativeSize int
    Type FileType
}
```
based on `ObjectStat`, ref: https://github.com/ipfs/interface-go-ipfs-core and https://godoc.org/github.com/ipfs/interface-go-ipfs-core#ObjectStat

Suggested call signature: 
```func (api *UnixfsAPI) Stat(ctx context.Context, p path.Path) (*iface.ObjectStat, error)```

**Comment by Stebalien** [comment]
Closing in favor of https://github.com/ipfs/interface-go-ipfs-core/issues/58. There needs to be an interface decision here first.
